// =============================================================
// Read and Complete / Listen and Type 自動生成用の例文バンク
//   B1〜C1 程度の平叙文。ディクテーション・クローズ両方に使う。
// =============================================================

export const SENTENCES: string[] = [
  "The library closes at nine on weekdays.",
  "Regular exercise can significantly improve your overall health.",
  "Researchers found that consistent sleep improves memory and focus.",
  "The committee decided to postpone the meeting until next week.",
  "Despite the heavy rain, the outdoor concert continued as planned.",
  "Many students believe that daily practice is the key to fluency.",
  "The new policy aims to reduce traffic in the city center.",
  "She carefully reviewed the report before sending it to her manager.",
  "The museum offers free admission on the first Sunday of every month.",
  "Scientists are developing more efficient ways to store renewable energy.",
  "A balanced diet and enough sleep are essential for good health.",
  "The professor explained the concept using a simple example.",
  "Online courses allow people to learn new skills at their own pace.",
  "The company announced a significant increase in annual profits.",
  "Reading widely helps you expand your vocabulary naturally.",
  "The bridge was closed for repairs after the recent storm.",
  "He submitted his application just before the deadline.",
  "Volunteers planted hundreds of trees along the river.",
  "The recipe requires fresh vegetables and a little olive oil.",
  "Public transportation is often cheaper than driving downtown.",
  "The author spent three years researching the historical novel.",
  "Climate change is affecting weather patterns around the world.",
  "The team worked late to finish the project on time.",
  "Learning a language requires patience and consistent effort.",
  "The hotel provides a free breakfast for all its guests.",
  "Modern smartphones can perform tasks that once required a computer.",
  "The doctor advised her to drink more water and rest.",
  "Several factors contributed to the success of the campaign.",
  "The conference attracted experts from more than thirty countries.",
  "Recycling helps reduce the amount of waste sent to landfills.",
  "The students presented their findings to the entire class.",
  "A good night of sleep can improve concentration the next day.",
  "The garden attracts butterflies throughout the summer months.",
  "The manager praised the team for their hard work and dedication.",
  "Tourists often underestimate how large the national park is.",
  "The software update fixed several important security issues.",
  "Fresh fruit and vegetables are usually cheaper at local markets.",
  "The lecture covered the basic principles of economics.",
  "Engineers tested the prototype under extreme conditions.",
  "The novel describes life in a small coastal village.",
  "Employees are encouraged to share their ideas during meetings.",
  "The train was delayed because of a signal failure.",
  "Daily journaling can help you reflect on your progress.",
  "The charity raised enough money to build a new school.",
  "Careful planning can prevent many common mistakes.",
];
