// 自動生成: DETレベルの追加語彙（英→日）。dictionary.ts / wordbank.ts から読み込む。
export const VOCAB: Record<string, string> = {
  "advocate": "支持する、提唱する",
  "allocate": "割り当てる",
  "assert": "主張する",
  "convey": "伝える",
  "derive": "導き出す",
  "foster": "育む、促進する",
  "hinder": "妨げる",
  "implement": "実施する",
  "justify": "正当化する",
  "refine": "改良する",
  "refute": "反論する",
  "undergo": "経験する、受ける",
  "validate": "検証する、認める",
  "attribute": "起因とする",
  "constitute": "構成する",
  "denote": "示す、意味する",
  "depict": "描写する",
  "discern": "識別する",
  "elucidate": "解明する",
  "encompass": "包含する",
  "entail": "伴う",
  "exemplify": "例示する",
  "facilitate": "容易にする",
  "formulate": "策定する",
  "highlight": "強調する",
  "impede": "妨げる",
  "incorporate": "取り入れる",
  "indicate": "示す",
  "interpret": "解釈する",
  "manipulate": "操作する",
  "negate": "否定する",
  "outline": "概説する",
  "postulate": "仮定する",
  "presume": "推定する",
  "prioritize": "優先する",
  "rectify": "是正する",
  "regulate": "規制する",
  "reiterate": "繰り返し述べる",
  "stipulate": "規定する",
  "substantiate": "立証する",
  "summarize": "要約する",
  "supplement": "補う",
  "synthesize": "統合する",
  "underpin": "支える、裏付ける",
  "warrant": "正当化する、保証する",
  "acute": "鋭い、深刻な",
  "adverse": "不利な、有害な",
  "coarse": "粗い、下品な",
  "drastic": "思い切った、抜本的な",
  "feeble": "弱々しい",
  "immense": "莫大な、広大な",
  "inherent": "本来備わった、固有の",
  "lavish": "贅沢な、豊富な",
  "marginal": "わずかな、周辺の",
  "rigid": "硬い、厳格な",
  "scarce": "乏しい、まれな",
  "tangible": "具体的な、有形の",
  "trivial": "ささいな",
  "vital": "極めて重要な",
  "sturdy": "頑丈な",
  "vague": "あいまいな",
  "meager": "乏しい、貧弱な",
  "potent": "強力な",
  "sleek": "なめらかな、洗練された",
  "barren": "不毛の",
  "vibrant": "活気ある",
  "murky": "濁った、不明瞭な",
  "dense": "密集した、濃い",
  "hostile": "敵対的な",
  "crude": "粗野な、未加工の",
  "lofty": "高尚な、そびえ立つ",
  "stark": "厳しい、明白な",
  "dreary": "陰気な、退屈な",
  "frail": "虚弱な、もろい",
  "supple": "しなやかな",
  "rampant": "はびこる",
  "sparse": "まばらな",
  "vast": "広大な",
  "dire": "切迫した、悲惨な",
  "hefty": "重い、多額の",
  "flimsy": "薄っぺらな、もろい",
  "prevalent": "広く普及した",
  "sober": "冷静な、地味な",
  "blatant": "露骨な",
  "serene": "穏やかな",
  "keen": "鋭い、熱心な",
  "vicious": "悪質な、激しい",
  "placid": "平穏な",
  "turbulent": "荒れた、激動の",
  "pristine": "汚れのない、新品同様の",
  "ambiguity": "曖昧さ",
  "adversity": "逆境、苦難",
  "affinity": "親近感、相性",
  "altruism": "利他主義",
  "ambivalence": "相反する感情",
  "apathy": "無関心",
  "aspiration": "願望、向上心",
  "candor": "率直さ",
  "coercion": "強制",
  "cohesion": "結束、団結",
  "complacency": "自己満足",
  "conjecture": "推測",
  "connotation": "言外の意味",
  "credibility": "信頼性",
  "deterrence": "抑止",
  "disparity": "格差、相違",
  "diversity": "多様性",
  "duplicity": "二枚舌、欺瞞",
  "equilibrium": "均衡",
  "futility": "無益さ",
  "humility": "謙虚さ",
  "ideology": "思想、理念",
  "impartiality": "公平さ",
  "ingenuity": "創意工夫",
  "insight": "洞察",
  "intuition": "直感",
  "legitimacy": "正当性",
  "longevity": "長寿、寿命",
  "morale": "士気",
  "mortality": "死亡率、死すべき運命",
  "novelty": "目新しさ",
  "obscurity": "無名、不明瞭",
  "paradigm": "枠組み、模範",
  "perception": "認識、知覚",
  "phenomenon": "現象",
  "prejudice": "偏見",
  "proximity": "近接",
  "reciprocity": "相互関係",
  "redemption": "救済、償い",
  "scarcity": "希少性、不足",
  "skepticism": "懐疑",
  "solidarity": "連帯",
  "stigma": "汚名",
  "transparency": "透明性",
  "validity": "妥当性",
  "versatility": "多才、汎用性",
  "asset": "資産、強み",
  "backlash": "強い反発",
  "census": "国勢調査",
  "commodity": "商品、産物",
  "deficit": "赤字、不足",
  "ecosystem": "生態系",
  "emission": "排出、排出物",
  "infrastructure": "社会基盤",
  "legislation": "法律、立法",
  "recession": "景気後退",
  "subsidy": "補助金",
  "welfare": "福祉",
  "inflation": "物価上昇、インフレ",
  "revenue": "収入、歳入",
  "poverty": "貧困",
  "unemployment": "失業",
  "surplus": "余剰、黒字",
  "taxation": "課税",
  "tariff": "関税",
  "liability": "負債、責任",
  "dividend": "配当金",
  "shortage": "不足、欠乏",
  "demand": "需要",
  "productivity": "生産性",
  "workforce": "労働力",
  "wage": "賃金",
  "pension": "年金",
  "investment": "投資",
  "deforestation": "森林伐採",
  "pollution": "汚染",
  "drought": "干ばつ",
  "famine": "飢饉",
  "habitat": "生息地",
  "biodiversity": "生物多様性",
  "sustainability": "持続可能性",
  "conservation": "保護、保全",
  "reservoir": "貯水池",
  "sewage": "下水、汚水",
  "contamination": "汚染、混入",
  "erosion": "浸食",
  "migration": "移住、移動",
  "inequality": "不平等",
  "prosperity": "繁栄",
  "commerce": "商業、貿易",
  "enterprise": "企業、事業",
  "monopoly": "独占",
  "enzyme": "酵素",
  "isotope": "同位体",
  "nucleus": "核、原子核",
  "electron": "電子",
  "neutron": "中性子",
  "proton": "陽子",
  "atom": "原子",
  "membrane": "膜、細胞膜",
  "tissue": "組織",
  "protein": "タンパク質",
  "chromosome": "染色体",
  "bacterium": "細菌",
  "fungus": "菌類",
  "vertebrate": "脊椎動物",
  "sediment": "堆積物",
  "mineral": "鉱物",
  "crystal": "結晶",
  "solvent": "溶媒",
  "solute": "溶質",
  "reagent": "試薬",
  "alloy": "合金",
  "acid": "酸",
  "voltage": "電圧",
  "current": "電流",
  "frequency": "周波数、頻度",
  "wavelength": "波長",
  "momentum": "運動量",
  "density": "密度",
  "viscosity": "粘度",
  "buoyancy": "浮力",
  "gravity": "重力",
  "inertia": "慣性",
  "friction": "摩擦",
  "temperature": "温度",
  "pressure": "圧力",
  "combustion": "燃焼",
  "oxidation": "酸化",
  "fermentation": "発酵",
  "respiration": "呼吸",
  "photosynthesis": "光合成",
  "metabolism": "代謝",
  "evolution": "進化",
  "galaxy": "銀河",
  "asteroid": "小惑星",
  "equation": "方程式",
  "variable": "変数",
  "aloof": "よそよそしい",
  "amiable": "愛想のよい",
  "apathetic": "無関心な",
  "audacious": "大胆な",
  "belligerent": "好戦的な",
  "benevolent": "慈悲深い",
  "boisterous": "騒々しい",
  "callous": "冷淡な",
  "compassionate": "思いやりのある",
  "contemptuous": "軽蔑的な",
  "courteous": "礼儀正しい",
  "defiant": "反抗的な",
  "despondent": "落胆した",
  "docile": "従順な",
  "dogmatic": "独断的な",
  "elated": "大喜びの",
  "empathetic": "共感的な",
  "flippant": "軽薄な",
  "forlorn": "わびしい",
  "frivolous": "軽薄な",
  "gracious": "丁重な",
  "haughty": "傲慢な",
  "impetuous": "衝動的な",
  "indignant": "憤慨した",
  "insolent": "無礼な",
  "jovial": "陽気な",
  "melancholy": "憂うつな",
  "meek": "おとなしい",
  "morose": "不機嫌な",
  "obstinate": "頑固な",
  "petulant": "短気な",
  "pompous": "尊大な",
  "remorseful": "後悔している",
  "sardonic": "冷笑的な",
  "servile": "卑屈な",
  "somber": "陰気な",
  "stoic": "冷静な",
  "sullen": "むっつりした",
  "taciturn": "無口な",
  "timid": "臆病な",
  "vindictive": "執念深い",
  "wary": "用心深い",
  "zealous": "熱心な",
  "accelerate": "加速する",
  "accompany": "同行する",
  "adhere": "固守する、付着する",
  "administer": "管理する、施す",
  "alter": "変える",
  "aspire": "切望する",
  "attain": "達成する",
  "avert": "回避する、そらす",
  "bolster": "強化する",
  "clarify": "明確にする",
  "coincide": "一致する",
  "compensate": "補償する",
  "comply": "従う",
  "conceal": "隠す",
  "cultivate": "育てる、養う",
  "curtail": "削減する",
  "deceive": "だます",
  "deplete": "使い果たす",
  "deter": "思いとどまらせる",
  "devise": "考案する",
  "disrupt": "混乱させる",
  "divert": "そらす、転換する",
  "dwindle": "次第に減る",
  "impose": "課す",
  "induce": "誘発する",
  "linger": "長居する、残る",
  "nurture": "育む",
  "omit": "省く",
  "oversee": "監督する",
  "penetrate": "貫通する",
  "ponder": "熟考する",
  "prevail": "打ち勝つ、普及する",
  "refrain": "控える",
  "relinquish": "手放す",
  "replicate": "複製する",
  "restrain": "抑制する",
  "retain": "保持する",
  "surpass": "上回る",
  "yearn": "切望する",
};

export const FAKE_WORDS_EXTRA: string[] = [
  "brimsel",
  "pondrate",
  "flurnex",
  "grappity",
  "snolent",
  "twindor",
  "cralmic",
  "plovish",
  "drentle",
  "marbick",
  "quavert",
  "snibrel",
  "tormish",
  "gleavon",
  "prindal",
  "swomber",
  "flantic",
  "creebish",
  "glomart",
  "vundle",
  "trampick",
  "blorsen",
  "quibnar",
  "frendle",
  "smolch",
  "plornate",
  "swivick",
  "crandel",
  "dropsen",
  "flemby",
  "grontish",
  "swabnel",
  "cluvert",
  "plindar",
  "brontal",
  "gleamic",
  "snorvel",
  "twibble",
  "frondel",
  "crampish",
  "dwillet",
  "glonser",
  "prabnic",
  "swendle",
  "blorvic",
  "trantle",
  "frindal",
  "gloomp",
  "snibvel",
  "quandic",
  "plomber",
  "drevish",
  "grombal",
  "snavick",
  "flandic",
  "prevish",
  "swornal",
  "gleckip",
  "blunsel",
  "trondal",
  "crepick",
  "smolvic",
  "plendar",
  "gravnel",
  "brundish",
  "flonker",
  "quemby",
  "swindal",
  "gromble",
  "plavert",
  "dronsic",
  "glembal",
  "trindor",
  "snormic",
  "flantel",
  "dwirgon",
  "plebick",
  "gromsel",
  "quandle",
  "trevish",
  "blonkar",
  "swendic",
  "plumret",
  "drenvel",
  "glombic",
  "snarpel",
  "froomby",
  "twandle",
];
